#status = error
#
#
#rootLogger.level = error
#rootLogger.appenderRefs = stdout
#rootLogger.appenderRef.stdout.ref = STDOUT
#
#appender.STDOUT.type = Console
#appender.STDOUT.name = STDOUT
#appender.STDOUT.layout.type = PatternLayout
#appender.STDOUT.layout.pattern = %m%n
#
#
#logger.spark.name = org.apache.spark
#logger.spark.level = error
#
#
#logger.hadoop.name = org.apache.hadoop
#logger.hadoop.level = error
#
#
#logger.mongo.name = com.mongodb
#logger.mongo.level = error
#
#
#logger.jetty.name = org.eclipse.jetty
#logger.jetty.level = error