import { Flex } from "@chakra-ui/react";
import { motion } from "framer-motion";
import Head from "next/head";
import { useRouter } from "next/router";

import ConversationsWrapper from "../components/Conversations/ConversationsWrapper";
import FeedWrapper from "../components/Feed/FeedWrapper";
import NoConversationSelected from "../components/Feed/NoConversationSelected";

type Props = {};

function ChatRoom({}: Props) {
  const router = useRouter();
  const {
    query: { userInCommunities, member },
  } = router;

  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Reddit Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/header.png" />
      </Head>
      <Flex height="100vh" overflow="hidden">
        <ConversationsWrapper />
        <Flex
          display={{ base: userInCommunities ? "flex" : "none", md: "flex" }}
          direction="column"
          width="100%"
        >
          <NoConversationSelected />
        </Flex>
      </Flex>
    </motion.div>
  );
}

export default ChatRoom;
