/**
 * Cached local profile images to avoid external network requests.
 * Using local assets prevents rate-limiting and improves performance.
 */
export const redditProfileImage = [
  "/images/redditlogo.png",
  "/images/redditFace.svg",
  "/images/header.png",
  "/images/redditPersonalHome.png",
  "/images/recCommsArt.png",
  "/images/not-found-512.webp",
  "/images/sgf6r5easbh31.jpg",
  "/images/xw6wqhhjubh31.webp",
  "/images/googlelogo.png",
  "/images/redditlogo.png",
  "/images/redditFace.svg",
  "/images/header.png",
  "/images/redditPersonalHome.png",
  "/images/recCommsArt.png",
  "/images/not-found-512.webp",
  "/images/sgf6r5easbh31.jpg",
  "/images/xw6wqhhjubh31.webp",
  "/images/googlelogo.png",
  "/images/redditlogo.png",
  "/images/redditFace.svg",
  "/images/header.png",
  "/images/redditPersonalHome.png",
  "/images/recCommsArt.png",
  "/images/not-found-512.webp",
  "/images/sgf6r5easbh31.jpg",
  "/images/xw6wqhhjubh31.webp",
  "/images/googlelogo.png",
  "/images/redditlogo.png",
  "/images/redditFace.svg",
  "/images/header.png",
  "/images/redditPersonalHome.png",
];
