package com.reddit.recommender.models

import org.apache.spark.sql.types._


object RedditSchema {
  val schema: StructType = new StructType()
    .add("kind", StringType)
    .add("query", StringType)
    .add("id", StringType)
    .add("title", StringType)
    .add("body", StringType)
    .add("author", StringType)
    .add("score", IntegerType)
    .add("upvote_ratio", DoubleType)
    .add("num_comments", IntegerType)
    .add("subreddit", StringType)
    .add("created_utc", StringType)
    .add("url", StringType)
    .add("flair", StringType)
    .add("over_18", BooleanType)
    .add("is_self", BooleanType)
    .add("spoiler", BooleanType)
    .add("locked", BooleanType)
    .add("is_video", BooleanType)
    .add("domain", StringType)
    .add("thumbnail", StringType)
    .add("url_overridden_by_dest", StringType)
    .add("author_fullname", StringType)
    .add("author_flair_text", StringType)
    .add("author_premium", BooleanType)
    .add("selftext_html", StringType)
    .add("postId", StringType)
    .add("parentId", StringType)
    .add("depth", IntegerType)
    .add("media", StringType)
    .add("media_metadata", StringType)
    .add("gallery_data", StringType)
    .add("stickied", BooleanType)
    .add("distinguished", StringType)
    .add("total_awards_received", IntegerType)
    .add("all_awardings", StringType)
    .add("gilded", IntegerType)
    .add("num_crossposts", IntegerType)
    .add("is_original_content", BooleanType)
    .add("preview", StringType)
    .add("secure_media", StringType)
    .add("secure_media_embed", StringType)
    .add("crosspost_parent_list", StringType)
    .add("is_comment", BooleanType)
    .add("treatment_tags", StringType)
    .add("post_hint", StringType)
    .add("author_cakeday", BooleanType)
    .add("num_reports", IntegerType)
    .add("approved_at_utc", StringType)
    .add("archived", BooleanType)
    .add("postUrl", StringType)
    .add("is_submitter", BooleanType)
    .add("score_hidden", BooleanType)
    .add("controversiality", IntegerType)
  
  
}